Repository ucfopen/canvasapi, pull requests merged in 2018-07, with the labels that each got.

#192 Add `get all quiz submissions` endpoint
  AUTHORS.md
  CHANGELOG.md
  canvasapi/quiz.py
  docs/quiz-ref.rst
  tests/fixtures/quiz.json
  tests/test_quiz.py
Labels: api-coverage

#198 Outcome Group Context
  canvasapi/outcome.py
  tests/fixtures/outcome.json
  tests/test_outcome.py
Labels: bug

#200 Add support for Python 3.7
  .travis.yml
  setup.py
Labels: enhancement
