Repository ucfopen/canvasapi, pull requests merged in 2019-11, with the labels that each got.

#333 Issue/332 list assignments
  canvasapi/assignment.py
  canvasapi/course.py
  tests/fixtures/course.json
  tests/test_course.py
Labels: api-coverage

#338 Add additional keyword arguments for get_user call
  canvasapi/canvas.py
  canvasapi/course.py
Labels: bug

#336 Issue/328 quiz submission user list
  canvasapi/quiz.py
  tests/fixtures/quiz.json
  tests/test_quiz.py
Labels: api-coverage

#339 Update iterable check
  canvasapi/util.py
Labels: bug

#340 GroupedSubmission submissions key:value deleted
  canvasapi/submission.py
  tests/test_submission.py
Labels: bug

#342 Deprecate CanvasObject.attributes and CanvasOject.to_json()
  CHANGELOG.md
  canvasapi/canvas_object.py
  tests/test_canvas_object.py
Labels: enhancement

#343 Add support for AssignmentOverrides inside Assignments
  CHANGELOG.md
  canvasapi/assignment.py
  tests/fixtures/assignment.json
  tests/test_assignment.py
Labels: api-coverage

#344 Release v0.15.0
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  AUTHORS.md
  CHANGELOG.md
  canvasapi/__init__.py
  canvasapi/account.py
  canvasapi/assignment.py
  canvasapi/authentication_event.py
  canvasapi/canvas.py
  canvasapi/canvas_object.py
  canvasapi/comm_message.py
  canvasapi/course.py
  canvasapi/gradebook_history.py
  canvasapi/group.py
  canvasapi/license.py
  canvasapi/login.py
  canvasapi/paginated_list.py
  canvasapi/quiz.py
  canvasapi/rubric.py
  canvasapi/submission.py
  canvasapi/usage_rights.py
  canvasapi/user.py
  canvasapi/util.py
  docs/assignment-ref.rst
  docs/authentication-event-ref.rst
  docs/class-reference.rst
  docs/comm-message-ref.rst
  docs/examples.rst
  docs/license-ref.rst
  docs/quiz-ref.rst
  docs/usage-rights-ref.rst
  tests/fixtures/account.json
  tests/fixtures/assignment.json
  tests/fixtures/comm_message.json
  tests/fixtures/course.json
  tests/fixtures/group.json
  tests/fixtures/login.json
  tests/fixtures/quiz.json
  tests/fixtures/rubric.json
  tests/fixtures/submission.json
  tests/fixtures/user.json
  tests/test_account.py
  tests/test_assignment.py
  tests/test_authentication_event.py
  tests/test_canvas.py
  tests/test_canvas_object.py
  tests/test_comm_messages.py
  tests/test_course.py
  tests/test_gradebook_history.py
  tests/test_group.py
  tests/test_licenses.py
  tests/test_login.py
  tests/test_paginated_list.py
  tests/test_quiz.py
  tests/test_rubric.py
  tests/test_submission.py
  tests/test_usage_rights.py
  tests/test_user.py
  tests/test_util.py
Labels: release
