Repository ucfopen/canvasapi, pull requests merged in 2020-11, with the labels that each got.

#428 Update contributing material
  .github/CONTRIBUTING.md
  README.md
Labels: hacktoberfest-accepted

#426 Issue/425 course todo items
  CHANGELOG.md
  canvasapi/course.py
  canvasapi/todo.py
  docs/class-reference.rst
  docs/todo-ref.rst
  tests/fixtures/course.json
  tests/test_course.py
  tests/test_todo.py
Labels: hacktoberfest-accepted

#434 Issue/411 create pairing code
  CHANGELOG.md
  canvasapi/pairing_code.py
  canvasapi/user.py
  docs/class-reference.rst
  docs/pairing-code-ref.rst
  tests/fixtures/user.json
  tests/test_pairing_code.py
  tests/test_user.py
Labels: hacktoberfest-accepted

#436 Added backwards-compatible support for canvas.get_announcements
  .gitignore
  CHANGELOG.md
  canvasapi/canvas.py
  tests/test_canvas.py
Labels: enhancement, hacktoberfest-accepted

#437 Deprecate Enrollment Type Argument in Enroll User
  CHANGELOG.md
  canvasapi/course.py
  tests/test_course.py
Labels: bug, hacktoberfest-accepted
