Repository ucfopen/canvasapi, pull requests merged in 2020-07, with the labels that each got.

#391 Fix API_URL
  canvasapi/canvas.py
  tests/test_canvas.py
Labels: bug

#392 Release v0.16.1
  CHANGELOG.md
  canvasapi/__init__.py
Labels: release

#394 Upgrade Ubuntu dist on Travis to bionic
  .travis.yml
Labels: backstage

#388 Remove deprecated methods and attributes
  CHANGELOG.md
  canvasapi/account.py
  canvasapi/canvas.py
  canvasapi/canvas_object.py
  canvasapi/communication_channel.py
  canvasapi/course.py
  canvasapi/current_user.py
  canvasapi/discussion_topic.py
  canvasapi/folder.py
  canvasapi/group.py
  canvasapi/module.py
  canvasapi/outcome.py
  canvasapi/page.py
  canvasapi/quiz.py
  canvasapi/section.py
  canvasapi/user.py
  canvasapi/util.py
  tests/fixtures/submission.json
  tests/test_account.py
  tests/test_canvas.py
  tests/test_canvas_object.py
  tests/test_communication_channel.py
  tests/test_course.py
  tests/test_current_user.py
  tests/test_discussion_topic.py
  tests/test_folder.py
  tests/test_group.py
  tests/test_module.py
  tests/test_outcome.py
  tests/test_page.py
  tests/test_quiz.py
  tests/test_section.py
  tests/test_submission.py
  tests/test_user.py
  tests/test_util.py
Labels: enhancement

#396 PyPI Deployment via Travis
  .travis.yml
  CHANGELOG.md
  DEPLOY.md
Labels: backstage

#398 Fix Quiz Group Course ID
  AUTHORS.md
  CHANGELOG.md
  canvasapi/quiz.py
  tests/fixtures/quiz.json
  tests/fixtures/quiz_group.json
  tests/test_quiz.py
  tests/test_quiz_group.py
Labels: bug

#403 Issue #402 Create External Tool - Client ID
  CHANGELOG.md
  canvasapi/course.py
  tests/test_course.py
Labels: api-coverage, bug

#404 Issue #295 custom gradebook columns
  AUTHORS.md
  CHANGELOG.md
  canvasapi/course.py
  canvasapi/custom_gradebook_columns.py
  canvasapi/quiz_group.py
  docs/class-reference.rst
  docs/custom-gradebook-columns-ref.rst
  tests/fixtures/course.json
  tests/fixtures/custom_gradebook_columns.json
  tests/test_course.py
  tests/test_custom_gradebook_columns.py
  tests/util.py
Labels: api-coverage

#406 Issue #350 create module item
  canvasapi/module.py
  tests/test_module.py
Labels: api-coverage
