Repository ucfopen/canvasapi, pull requests merged in 2020-06, with the labels that each got.

#377 changing all instances of l to lic in relevant tests to appease flake8
  tests/test_course.py
  tests/test_group.py
  tests/test_user.py
Labels: backstage, bug

#355 issue/354 graphql support
  canvasapi/canvas.py
  canvasapi/exceptions.py
  canvasapi/requester.py
  docs/exceptions.rst
  tests/fixtures/graphql.json
  tests/fixtures/requests.json
  tests/settings.py
  tests/test_canvas.py
  tests/test_requester.py
  tests/util.py
Labels: api-coverage, enhancement

#382 Release v0.16.0
  .gitignore
  CHANGELOG.md
  canvasapi/__init__.py
  canvasapi/account.py
  canvasapi/blueprint.py
  canvasapi/canvas.py
  canvasapi/course.py
  canvasapi/exceptions.py
  canvasapi/quiz.py
  canvasapi/requester.py
  docs/course-ref.rst
  docs/exceptions.rst
  docs/quiz-ref.rst
  tests/fixtures/account.json
  tests/fixtures/course.json
  tests/fixtures/graphql.json
  tests/fixtures/quiz.json
  tests/fixtures/requests.json
  tests/settings.py
  tests/test_account.py
  tests/test_blueprint.py
  tests/test_canvas.py
  tests/test_course.py
  tests/test_group.py
  tests/test_quiz.py
  tests/test_requester.py
  tests/test_user.py
  tests/util.py
Labels: release
