Repository ucfopen/canvasapi, pull requests merged in 2021-03, with the labels that each got.

#468 #445 GitHub Actions
  .github/workflows/run-tests.yml
  CHANGELOG.md
  scripts/find_missing_kwargs.py
  setup.cfg
Labels: backstage

#473 Run GH Actions on PR events
  .github/workflows/run-tests.yml
Labels: backstage

#471 Fix Create Poll Parameter
  CHANGELOG.md
  canvasapi/canvas.py
  tests/test_canvas.py
  tests/test_poll.py
Labels: bug

#474 Python 3.9
  .github/workflows/run-tests.yml
  CHANGELOG.md
  setup.py
Labels: enhancement

#469 #465: Provisional Grades
  AUTHORS.md
  CHANGELOG.md
  canvasapi/assignment.py
  canvasapi/submission.py
  tests/fixtures/assignment.json
  tests/test_assignment.py
Labels: api-coverage

#476 Issue #475 GitHub Actions Coverage
  .github/workflows/run-tests.yml
Labels: backstage

#478 Remove Travis CI
  .travis.yml
  CHANGELOG.md
Labels: backstage

#477 Deploy to PyPI with GitHub Actions
  .github/workflows/deploy.yml
  DEPLOY.md
Labels: backstage

#479 Release v2.2.0
  .github/workflows/deploy.yml
  .github/workflows/run-tests.yml
  .travis.yml
  AUTHORS.md
  CHANGELOG.md
  DEPLOY.md
  README.md
  canvasapi/__init__.py
  canvasapi/assignment.py
  canvasapi/canvas.py
  canvasapi/course.py
  canvasapi/enrollment.py
  canvasapi/exceptions.py
  canvasapi/favorite.py
  canvasapi/folder.py
  canvasapi/group.py
  canvasapi/requester.py
  canvasapi/section.py
  canvasapi/submission.py
  canvasapi/upload.py
  canvasapi/user.py
  docs/exceptions.rst
  docs/getting-started.rst
  scripts/find_missing_kwargs.py
  setup.cfg
  setup.py
  tests/fixtures/assignment.json
  tests/fixtures/course.json
  tests/fixtures/current_user.json
  tests/fixtures/group.json
  tests/fixtures/requests.json
  tests/fixtures/section.json
  tests/fixtures/user.json
  tests/test_assignment.py
  tests/test_canvas.py
  tests/test_course.py
  tests/test_favorite.py
  tests/test_group.py
  tests/test_poll.py
  tests/test_requester.py
  tests/test_section.py
  tests/test_uploader.py
  tests/test_user.py
Labels: release
