Repository ucfopen/canvasapi, pull requests merged in 2022-09, with the labels that each got.

#549 GitHub Actions badge
  README.md
Labels: documentation, backstage

#551 Update Coverage Badge
  README.md
Labels: documentation, backstage

#512 Parse `attachments` attribute in `canvasapi.submission.Submission`
  AUTHORS.md
  CHANGELOG.md
  canvasapi/submission.py
  tests/fixtures/submission.json
  tests/test_submission.py
Labels: enhancement

#555 Release v3.0.0
  .github/workflows/run-tests.yml
  AUTHORS.md
  CHANGELOG.md
  README.md
  canvasapi/__init__.py
  canvasapi/account.py
  canvasapi/assignment.py
  canvasapi/canvas.py
  canvasapi/canvas_object.py
  canvasapi/content_migration.py
  canvasapi/course.py
  canvasapi/eportfolio.py
  canvasapi/grade_change_log.py
  canvasapi/outcome.py
  canvasapi/quiz.py
  canvasapi/quiz_group.py
  canvasapi/rubric.py
  canvasapi/submission.py
  canvasapi/user.py
  dev_requirements.txt
  docs/account-ref.rst
  docs/class-reference.rst
  docs/content-migration-ref.rst
  docs/course-ref.rst
  docs/eportfolio-ref.rst
  docs/getting-started.rst
  docs/grade-change-log-ref.rst
  docs/outcome-ref.rst
  requirements.txt
  setup.py
  tests/fixtures/account.json
  tests/fixtures/assignment.json
  tests/fixtures/content_migration.json
  tests/fixtures/course.json
  tests/fixtures/eportfolio.json
  tests/fixtures/outcome.json
  tests/fixtures/rubric.json
  tests/fixtures/submission.json
  tests/fixtures/user.json
  tests/test_account.py
  tests/test_assignment.py
  tests/test_canvas.py
  tests/test_canvas_object.py
  tests/test_content_migration.py
  tests/test_course.py
  tests/test_eportfolio.py
  tests/test_grade_change_log.py
  tests/test_outcome.py
  tests/test_quiz.py
  tests/test_quiz_group.py
  tests/test_rubric.py
  tests/test_submission.py
  tests/test_user.py
  tests_requirements.txt
Labels: release
