Repository ucfopen/canvasapi, pull requests merged in 2023-05, with the labels that each got.

#614 Update `PaginatedList`
  CHANGELOG.md
  canvasapi/paginated_list.py
  tests/fixtures/paginated_list.json
  tests/test_paginated_list.py
Labels: enhancement

#612 New Quizzes
  CHANGELOG.md
  canvasapi/course.py
  canvasapi/new_quiz.py
  canvasapi/paginated_list.py
  tests/fixtures/new_quiz.json
  tests/settings.py
  tests/test_course.py
  tests/test_new_quiz.py
Labels: api-coverage

#622 Course Create Discussion Attach Files #621
  CHANGELOG.md
  canvasapi/course.py
  canvasapi/requester.py
  tests/fixtures/generic_file.txt
  tests/test_course.py
Labels: bug

#624 Delete method for course and group pages
  AUTHORS.md
  CHANGELOG.md
  canvasapi/page.py
  tests/fixtures/page.json
  tests/test_page.py
Labels: api-coverage

#625 Add support for Python 3.11
  .github/workflows/run-tests.yml
  CHANGELOG.md
  setup.py
Labels: backstage
