Repository ucfopen/canvasapi, pull requests merged in 2023-04, with the labels that each got.

#567 Added endpoints for querying CourseEvent objects
  CHANGELOG.md
  canvasapi/account.py
  canvasapi/communication_channel.py
  canvasapi/course.py
  canvasapi/course_event.py
  canvasapi/paginated_list.py
  docs/class-reference.rst
  docs/conf.py
  docs/course-event-ref.rst
  scripts/validate_docstrings.py
  tests/fixtures/account.json
  tests/fixtures/course.json
  tests/test_account.py
  tests/test_canvas.py
  tests/test_course.py
  tests/test_course_event.py
  tests/test_favorite.py
  tests/test_gradebook_history.py
  tests/test_grading_period.py
  tests/test_outcome_import.py
  tests/test_page.py
  tests/test_scope.py
  tests/test_submission.py
  tests/test_user.py
  tests/test_util.py
  tests_requirements.txt
Labels: api-coverage, hacktoberfest-accepted

#592 Fixes #584
  CHANGELOG.md
  canvasapi/account.py
  canvasapi/course.py
  canvasapi/user.py
  tests/fixtures/account.json
  tests/fixtures/course.json
  tests/fixtures/user.json
  tests/test_account.py
  tests/test_course.py
  tests/test_user.py
Labels: bug

#575 Updating documentation to include references to AssignmentOverride an…
  AUTHORS.md
  CHANGELOG.md
  canvasapi/assignment.py
  docs/assignment-ref.rst
Labels: documentation
